//! Build-time utilities for generating type-safe locale keys.
//!
//! This module is only available when the `codegen` feature is enabled.

use std::collections::HashSet;
use std::fs;
use std::path::Path;

/// Scans the given `content_path` for translation keys and generates a Rust file
/// containing a strictly-typed `LocKey` enum. The file is saved to `out_dir` as `vernacular_keys.rs`.
pub fn generate_keys<P: AsRef<Path>, Q: AsRef<Path>>(content_path: P, out_dir: Q) {
    let content_path = content_path.as_ref();
    let out_dir = out_dir.as_ref();

    let mut unique_keys: HashSet<String> = HashSet::new();

    let mut dirs_to_visit = vec![content_path.to_path_buf()];
    while let Some(dir) = dirs_to_visit.pop() {
        if let Ok(entries) = fs::read_dir(&dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    dirs_to_visit.push(path);
                } else if path.is_file() {
                    let ext = path.extension().and_then(|e| e.to_str());
                    let is_root = path.parent() == Some(content_path);

                    #[cfg(feature = "csv")]
                    if ext == Some("csv") {
                        match crate::parsing::csv::scan_keys(&path, is_root) {
                            Ok(keys) => {
                                for k in keys {
                                    unique_keys.insert(k);
                                }
                            }
                            Err(e) => {
                                println!(
                                    "cargo:warning=Failed to scan keys from {}: {}",
                                    path.display(),
                                    e
                                );
                            }
                        }
                    }

                    #[cfg(feature = "ron")]
                    if ext == Some("ron") {
                        match crate::parsing::ron::scan_keys(&path) {
                            Ok(keys) => {
                                for k in keys {
                                    unique_keys.insert(k);
                                }
                            }
                            Err(e) => {
                                println!(
                                    "cargo:warning=Failed to scan keys from {}: {}",
                                    path.display(),
                                    e
                                );
                            }
                        }
                    }
                }
            }
        }
    }

    let mut sorted_keys: Vec<_> = unique_keys.into_iter().collect();
    sorted_keys.sort();

    let mut enum_variants = String::new();
    let mut match_arms = String::new();

    for key in sorted_keys {
        let pascal_case = to_pascal_case(&key);
        enum_variants.push_str(&format!("    {pascal_case},\n"));
        match_arms.push_str(&format!(
            "            LocKey::{pascal_case} => \"{key}\",\n"
        ));
    }

    let generated_code = format!(
        r#"// @generated by vernacular

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LocKey {{
{enum_variants}
}}

impl AsRef<str> for LocKey {{
    fn as_ref(&self) -> &str {{
        match self {{
{match_arms}
        }}
    }}
}}

impl std::fmt::Display for LocKey {{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        write!(f, "{{}}", self.as_ref())
    }}
}}
"#
    );

    let out_file = out_dir.join("vernacular_keys.rs");
    fs::write(out_file, generated_code).expect("Failed to write vernacular_keys.rs");
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    let mut capitalize_next = true;

    for c in s.chars() {
        if c == '.' || c == '_' || c == '-' || c == ' ' {
            capitalize_next = true;
        } else if capitalize_next {
            result.extend(c.to_uppercase());
            capitalize_next = false;
        } else {
            result.push(c);
        }
    }

    if result.is_empty() {
        result.push_str("Empty");
    } else if result.chars().next().unwrap().is_ascii_digit() {
        result.insert_str(0, "Key");
    }

    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_pascal_case() {
        assert_eq!(
            to_pascal_case("ui.main_menu.start_game"),
            "UiMainMenuStartGame"
        );
        assert_eq!(to_pascal_case("dialogue-greeting"), "DialogueGreeting");
        assert_eq!(to_pascal_case("some_key_with_123"), "SomeKeyWith123");
        assert_eq!(to_pascal_case("1st_place"), "Key1stPlace"); // Handles starting numbers
        assert_eq!(to_pascal_case(""), "Empty"); // Handles empty
        assert_eq!(to_pascal_case("..."), "Empty"); // Handles pure symbols resolving to empty
    }

    #[test]
    fn test_cross_platform_path_handling() {
        use std::path::PathBuf;
        let path = PathBuf::from("assets").join("loc").join("ui.csv");
        assert!(path.to_str().unwrap().contains("assets"));
    }

    #[test]
    fn test_phantom_variant_ignored() {
        let dir = tempfile::tempdir().unwrap();
        let content_path = dir.path();

        // Root CSV with non-standard header
        let root_csv = content_path.join("root.csv");
        fs::write(root_csv, "id,en_US\nitems.shield,Shield").unwrap();

        let out_dir = tempfile::tempdir().unwrap();
        super::generate_keys(content_path, out_dir.path());

        let generated = fs::read_to_string(out_dir.path().join("vernacular_keys.rs")).unwrap();
        assert!(!generated.contains("LocKey::Id"));
        assert!(generated.contains("LocKey::ItemsShield"));
    }
}
